version: '3'

services:
    web:
        env_file: .env
        build: .
        restart: always
        container_name: comoestouhoje-be
        ports: ['4003:4003']
        volumes:
            - .:/app
        command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --reload --port 4003'
